apiVersion: v1
kind: Service
metadata:
  name: group-rpc
  labels:
    app: group-rpc
    app.kubernetes.io/name: group-rpc
    app.kubernetes.io/component: group
spec:
  selector:
    app: group-rpc
  ports:
  - port: 20300
    targetPort: 20300
    name: http
