Name: push.rpc
ListenOn: 0.0.0.0:20700
Postgres:
  DSN: postgres://im:im@host.docker.internal:5432/im?sslmode=disable
Log:
  ServiceName: push-rpc
  Mode: console
  Level: info
  Stat: false
RedisStore:
  Addr: host.docker.internal:6379
