Name: push.rpc
ListenOn: 0.0.0.0:20700
MySQL:
  DSN: im:im@tcp(localhost:3306)/im?parseTime=true&charset=utf8mb4&loc=Local
Log:
  ServiceName: push-rpc
  Mode: console
  Level: info
  Stat: false
RedisStore:
  Addr: host.docker.internal:6379
