Name: friend.rpc
ListenOn: 0.0.0.0:20200
MySQL:
  DSN: im:im@tcp(localhost:3306)/im?parseTime=true&charset=utf8mb4&loc=Local
Log:
  ServiceName: friend-rpc
  Mode: console
  Level: info
  Stat: false
ConversationRpc:
  Endpoints:
    - conversation-rpc:20400
