// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: push.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetOnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOnlineReq) Reset() {
	*x = SetOnlineReq{}
	mi := &file_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineReq) ProtoMessage() {}

func (x *SetOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineReq.ProtoReflect.Descriptor instead.
func (*SetOnlineReq) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{0}
}

func (x *SetOnlineReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SetOnlineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOnlineResp) Reset() {
	*x = SetOnlineResp{}
	mi := &file_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOnlineResp) ProtoMessage() {}

func (x *SetOnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOnlineResp.ProtoReflect.Descriptor instead.
func (*SetOnlineResp) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{1}
}

type GroupSubscribeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSubscribeReq) Reset() {
	*x = GroupSubscribeReq{}
	mi := &file_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSubscribeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSubscribeReq) ProtoMessage() {}

func (x *GroupSubscribeReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSubscribeReq.ProtoReflect.Descriptor instead.
func (*GroupSubscribeReq) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{2}
}

func (x *GroupSubscribeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupSubscribeReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupSubscribeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSubscribeResp) Reset() {
	*x = GroupSubscribeResp{}
	mi := &file_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSubscribeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSubscribeResp) ProtoMessage() {}

func (x *GroupSubscribeResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSubscribeResp.ProtoReflect.Descriptor instead.
func (*GroupSubscribeResp) Descriptor() ([]byte, []int) {
	return file_push_proto_rawDescGZIP(), []int{3}
}

var File_push_proto protoreflect.FileDescriptor

const file_push_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"push.proto\x12\x04push\"'\n" +
	"\fSetOnlineReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x0f\n" +
	"\rSetOnlineResp\"G\n" +
	"\x11GroupSubscribeReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\"\x14\n" +
	"\x12GroupSubscribeResp2\x81\x01\n" +
	"\x04Push\x124\n" +
	"\tSetOnline\x12\x12.push.SetOnlineReq\x1a\x13.push.SetOnlineResp\x12C\n" +
	"\x0eGroupSubscribe\x12\x17.push.GroupSubscribeReq\x1a\x18.push.GroupSubscribeRespB\bZ\x06./pushb\x06proto3"

var (
	file_push_proto_rawDescOnce sync.Once
	file_push_proto_rawDescData []byte
)

func file_push_proto_rawDescGZIP() []byte {
	file_push_proto_rawDescOnce.Do(func() {
		file_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)))
	})
	return file_push_proto_rawDescData
}

var file_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_push_proto_goTypes = []any{
	(*SetOnlineReq)(nil),       // 0: push.SetOnlineReq
	(*SetOnlineResp)(nil),      // 1: push.SetOnlineResp
	(*GroupSubscribeReq)(nil),  // 2: push.GroupSubscribeReq
	(*GroupSubscribeResp)(nil), // 3: push.GroupSubscribeResp
}
var file_push_proto_depIdxs = []int32{
	0, // 0: push.Push.SetOnline:input_type -> push.SetOnlineReq
	2, // 1: push.Push.GroupSubscribe:input_type -> push.GroupSubscribeReq
	1, // 2: push.Push.SetOnline:output_type -> push.SetOnlineResp
	3, // 3: push.Push.GroupSubscribe:output_type -> push.GroupSubscribeResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_push_proto_init() }
func file_push_proto_init() {
	if File_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_proto_rawDesc), len(file_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_proto_goTypes,
		DependencyIndexes: file_push_proto_depIdxs,
		MessageInfos:      file_push_proto_msgTypes,
	}.Build()
	File_push_proto = out.File
	file_push_proto_goTypes = nil
	file_push_proto_depIdxs = nil
}
