Name: cron
HealthPort: 10800
Postgres:
  DSN: postgres://im:im@host.docker.internal:5432/im?sslmode=disable
Redis:
  Addr: host.docker.internal:6379
RocketMQ:
  NameServer:
    - host.docker.internal:9876
Cron:
  InboxMergeMs: 100
  OfflineMergeSec: 10
  MemberBatch: 500
