apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: im
  app.kubernetes.io/component: cron
resources:
  - cron-configmap.yaml
  - cron-deployment.yaml
  - cron-service.yaml
