// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: friend.proto

package friend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AreFriendsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserA         int64                  `protobuf:"varint,1,opt,name=user_a,json=userA,proto3" json:"user_a,omitempty"`
	UserB         int64                  `protobuf:"varint,2,opt,name=user_b,json=userB,proto3" json:"user_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreFriendsReq) Reset() {
	*x = AreFriendsReq{}
	mi := &file_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreFriendsReq) ProtoMessage() {}

func (x *AreFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreFriendsReq.ProtoReflect.Descriptor instead.
func (*AreFriendsReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{0}
}

func (x *AreFriendsReq) GetUserA() int64 {
	if x != nil {
		return x.UserA
	}
	return 0
}

func (x *AreFriendsReq) GetUserB() int64 {
	if x != nil {
		return x.UserB
	}
	return 0
}

type AreFriendsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreFriendsResp) Reset() {
	*x = AreFriendsResp{}
	mi := &file_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreFriendsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreFriendsResp) ProtoMessage() {}

func (x *AreFriendsResp) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreFriendsResp.ProtoReflect.Descriptor instead.
func (*AreFriendsResp) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{1}
}

func (x *AreFriendsResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AcceptFriendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendReq) Reset() {
	*x = AcceptFriendReq{}
	mi := &file_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendReq) ProtoMessage() {}

func (x *AcceptFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendReq.ProtoReflect.Descriptor instead.
func (*AcceptFriendReq) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptFriendReq) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *AcceptFriendReq) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

type AcceptFriendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendResp) Reset() {
	*x = AcceptFriendResp{}
	mi := &file_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendResp) ProtoMessage() {}

func (x *AcceptFriendResp) ProtoReflect() protoreflect.Message {
	mi := &file_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendResp.ProtoReflect.Descriptor instead.
func (*AcceptFriendResp) Descriptor() ([]byte, []int) {
	return file_friend_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptFriendResp) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

var File_friend_proto protoreflect.FileDescriptor

const file_friend_proto_rawDesc = "" +
	"\n" +
	"\ffriend.proto\x12\x06friend\"=\n" +
	"\rAreFriendsReq\x12\x15\n" +
	"\x06user_a\x18\x01 \x01(\x03R\x05userA\x12\x15\n" +
	"\x06user_b\x18\x02 \x01(\x03R\x05userB\" \n" +
	"\x0eAreFriendsResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Q\n" +
	"\x0fAcceptFriendReq\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\"+\n" +
	"\x10AcceptFriendResp\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId2\x88\x01\n" +
	"\x06Friend\x12;\n" +
	"\n" +
	"AreFriends\x12\x15.friend.AreFriendsReq\x1a\x16.friend.AreFriendsResp\x12A\n" +
	"\fAcceptFriend\x12\x17.friend.AcceptFriendReq\x1a\x18.friend.AcceptFriendRespB\n" +
	"Z\b./friendb\x06proto3"

var (
	file_friend_proto_rawDescOnce sync.Once
	file_friend_proto_rawDescData []byte
)

func file_friend_proto_rawDescGZIP() []byte {
	file_friend_proto_rawDescOnce.Do(func() {
		file_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)))
	})
	return file_friend_proto_rawDescData
}

var file_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_friend_proto_goTypes = []any{
	(*AreFriendsReq)(nil),    // 0: friend.AreFriendsReq
	(*AreFriendsResp)(nil),   // 1: friend.AreFriendsResp
	(*AcceptFriendReq)(nil),  // 2: friend.AcceptFriendReq
	(*AcceptFriendResp)(nil), // 3: friend.AcceptFriendResp
}
var file_friend_proto_depIdxs = []int32{
	0, // 0: friend.Friend.AreFriends:input_type -> friend.AreFriendsReq
	2, // 1: friend.Friend.AcceptFriend:input_type -> friend.AcceptFriendReq
	1, // 2: friend.Friend.AreFriends:output_type -> friend.AreFriendsResp
	3, // 3: friend.Friend.AcceptFriend:output_type -> friend.AcceptFriendResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_friend_proto_init() }
func file_friend_proto_init() {
	if File_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_friend_proto_rawDesc), len(file_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_friend_proto_goTypes,
		DependencyIndexes: file_friend_proto_depIdxs,
		MessageInfos:      file_friend_proto_msgTypes,
	}.Build()
	File_friend_proto = out.File
	file_friend_proto_goTypes = nil
	file_friend_proto_depIdxs = nil
}
