// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type IdPathReq struct {
	Id int64 `path:"id"`
}

type Notification struct {
	Id       int64  `json:"id"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	Category string `json:"category"`
	Read     bool   `json:"read"`
}

type NotificationsResp struct {
	Notifications []Notification `json:"notifications"`
}

type StatusResp struct {
	Status string `json:"status"`
}
