// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthResp struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type DevTokenReq struct {
	UserId int64 `json:"user_id"`
}

type DevTokenResp struct {
	Token  string `json:"token"`
	UserId int64  `json:"user_id"`
	User   User   `json:"user"`
}

type DeviceReq struct {
	DeviceId  string `json:"device_id"`
	PushToken string `json:"push_token,optional"`
	Platform  string `json:"platform,optional"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
}

type StatusResp struct {
	Status string `json:"status"`
}

type User struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatar_url"`
}
