// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package message_client

import (
	"context"

	"im/apps/message/rpc/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ListMessagesReq  = message.ListMessagesReq
	ListMessagesResp = message.ListMessagesResp
	MessageItem      = message.MessageItem
	SendReq          = message.SendReq
	SendResp         = message.SendResp

	Message interface {
		Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error)
		ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) Send(ctx context.Context, in *SendReq, opts ...grpc.CallOption) (*SendResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.Send(ctx, in, opts...)
}

func (m *defaultMessage) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.ListMessages(ctx, in, opts...)
}
