// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package server

import (
	"context"

	"im/apps/notification/rpc/internal/logic"
	"im/apps/notification/rpc/internal/svc"
	"im/apps/notification/rpc/notification"
)

type NotificationServer struct {
	svcCtx *svc.ServiceContext
	notification.UnimplementedNotificationServer
}

func NewNotificationServer(svcCtx *svc.ServiceContext) *NotificationServer {
	return &NotificationServer{
		svcCtx: svcCtx,
	}
}

func (s *NotificationServer) SendSystem(ctx context.Context, in *notification.SendSystemReq) (*notification.SendSystemResp, error) {
	l := logic.NewSendSystemLogic(ctx, s.svcCtx)
	return l.SendSystem(in)
}
