// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package server

import (
	"context"

	"im/apps/group/rpc/group"
	"im/apps/group/rpc/internal/logic"
	"im/apps/group/rpc/internal/svc"
)

type GroupServer struct {
	svcCtx *svc.ServiceContext
	group.UnimplementedGroupServer
}

func NewGroupServer(svcCtx *svc.ServiceContext) *GroupServer {
	return &GroupServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupServer) IsMember(ctx context.Context, in *group.IsMemberReq) (*group.IsMemberResp, error) {
	l := logic.NewIsMemberLogic(ctx, s.svcCtx)
	return l.IsMember(in)
}

func (s *GroupServer) ListMembers(ctx context.Context, in *group.ListMembersReq) (*group.ListMembersResp, error) {
	l := logic.NewListMembersLogic(ctx, s.svcCtx)
	return l.ListMembers(in)
}

func (s *GroupServer) GetGroup(ctx context.Context, in *group.GetGroupReq) (*group.GetGroupResp, error) {
	l := logic.NewGetGroupLogic(ctx, s.svcCtx)
	return l.GetGroup(in)
}
