// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: push.proto

package server

import (
	"context"

	"im/apps/push/rpc/internal/logic"
	"im/apps/push/rpc/internal/svc"
	"im/apps/push/rpc/push"
)

type PushServer struct {
	svcCtx *svc.ServiceContext
	push.UnimplementedPushServer
}

func NewPushServer(svcCtx *svc.ServiceContext) *PushServer {
	return &PushServer{
		svcCtx: svcCtx,
	}
}

func (s *PushServer) SetOnline(ctx context.Context, in *push.SetOnlineReq) (*push.SetOnlineResp, error) {
	l := logic.NewSetOnlineLogic(ctx, s.svcCtx)
	return l.SetOnline(in)
}

func (s *PushServer) GroupSubscribe(ctx context.Context, in *push.GroupSubscribeReq) (*push.GroupSubscribeResp, error) {
	l := logic.NewGroupSubscribeLogic(ctx, s.svcCtx)
	return l.GroupSubscribe(in)
}
