// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user_client

import (
	"context"

	"im/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetUsersReq  = user.BatchGetUsersReq
	BatchGetUsersResp = user.BatchGetUsersResp
	GetUserReq        = user.GetUserReq
	GetUserResp       = user.GetUserResp
	UserInfo          = user.UserInfo
	ValidateTokenReq  = user.ValidateTokenReq
	ValidateTokenResp = user.ValidateTokenResp

	User interface {
		ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
		GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
		BatchGetUsers(ctx context.Context, in *BatchGetUsersReq, opts ...grpc.CallOption) (*BatchGetUsersResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) BatchGetUsers(ctx context.Context, in *BatchGetUsersReq, opts ...grpc.CallOption) (*BatchGetUsersResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.BatchGetUsers(ctx, in, opts...)
}
