// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package server

import (
	"context"

	"im/apps/message/rpc/internal/logic"
	"im/apps/message/rpc/internal/svc"
	"im/apps/message/rpc/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Send(ctx context.Context, in *message.SendReq) (*message.SendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *MessageServer) ListMessages(ctx context.Context, in *message.ListMessagesReq) (*message.ListMessagesResp, error) {
	l := logic.NewListMessagesLogic(ctx, s.svcCtx)
	return l.ListMessages(in)
}
