// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package server

import (
	"context"

	"im/apps/friend/rpc/friend"
	"im/apps/friend/rpc/internal/logic"
	"im/apps/friend/rpc/internal/svc"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServer) AreFriends(ctx context.Context, in *friend.AreFriendsReq) (*friend.AreFriendsResp, error) {
	l := logic.NewAreFriendsLogic(ctx, s.svcCtx)
	return l.AreFriends(in)
}

func (s *FriendServer) AcceptFriend(ctx context.Context, in *friend.AcceptFriendReq) (*friend.AcceptFriendResp, error) {
	l := logic.NewAcceptFriendLogic(ctx, s.svcCtx)
	return l.AcceptFriend(in)
}
