// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ConvPathReq struct {
	Id string `path:"id"`
}

type Conversation struct {
	Id          string `json:"id"`
	Type        string `json:"type"`
	GroupId     int64  `json:"group_id,omitempty"`
	GroupName   string `json:"group_name,omitempty"`
	PeerUserId  int64  `json:"peer_user_id,omitempty"`
	LastSeq     int64  `json:"last_seq"`
	LastPreview string `json:"last_preview"`
	Unread      int64  `json:"unread"`
	Pinned      bool   `json:"pinned"`
	Muted       bool   `json:"muted"`
}

type ConversationsResp struct {
	Conversations []Conversation `json:"conversations"`
}

type ListConversationsReq struct {
	DirectDays *int `form:"direct_days,optional"`
}

type MarkReadPathReq struct {
	Id  string `path:"id"`
	Seq int64  `json:"seq"`
}

type MarkReadReq struct {
	Seq int64 `json:"seq"`
}

type StatusResp struct {
	Status string `json:"status"`
}
