// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package group_client

import (
	"context"

	"im/apps/group/rpc/group"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetGroupReq     = group.GetGroupReq
	GetGroupResp    = group.GetGroupResp
	GroupInfo       = group.GroupInfo
	IsMemberReq     = group.IsMemberReq
	IsMemberResp    = group.IsMemberResp
	ListMembersReq  = group.ListMembersReq
	ListMembersResp = group.ListMembersResp

	Group interface {
		IsMember(ctx context.Context, in *IsMemberReq, opts ...grpc.CallOption) (*IsMemberResp, error)
		ListMembers(ctx context.Context, in *ListMembersReq, opts ...grpc.CallOption) (*ListMembersResp, error)
		GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error)
	}

	defaultGroup struct {
		cli zrpc.Client
	}
)

func NewGroup(cli zrpc.Client) Group {
	return &defaultGroup{
		cli: cli,
	}
}

func (m *defaultGroup) IsMember(ctx context.Context, in *IsMemberReq, opts ...grpc.CallOption) (*IsMemberResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.IsMember(ctx, in, opts...)
}

func (m *defaultGroup) ListMembers(ctx context.Context, in *ListMembersReq, opts ...grpc.CallOption) (*ListMembersResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.ListMembers(ctx, in, opts...)
}

func (m *defaultGroup) GetGroup(ctx context.Context, in *GetGroupReq, opts ...grpc.CallOption) (*GetGroupResp, error) {
	client := group.NewGroupClient(m.cli.Conn())
	return client.GetGroup(ctx, in, opts...)
}
