// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AcceptResp struct {
	Status string `json:"status"`
	ConvId string `json:"conv_id"`
}

type CheckResp struct {
	Friends bool `json:"friends"`
}

type FriendReq struct {
	UserId int64 `json:"user_id"`
}

type FriendsResp struct {
	Friends []User `json:"friends"`
}

type User struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	AvatarUrl string `json:"avatar_url"`
}
