// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddMembersPathReq struct {
	Id      int64   `path:"id"`
	UserIds []int64 `json:"user_ids"`
}

type AddMembersReq struct {
	UserIds []int64 `json:"user_ids"`
}

type CreateGroupReq struct {
	Name      string  `json:"name"`
	MemberIds []int64 `json:"member_ids,optional"`
}

type CreateGroupResp struct {
	Group  Group  `json:"group"`
	ConvId string `json:"conv_id"`
}

type Group struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	OwnerId    int64  `json:"owner_id"`
	MaxMembers int    `json:"max_members"`
	Notice     string `json:"notice"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type ListMembersReq struct {
	Id     int64 `path:"id"`
	Cursor int64 `form:"cursor,optional"`
}

type ListMembersResp struct {
	UserIds    []int64 `json:"user_ids"`
	NextCursor int64   `json:"next_cursor"`
}

type StatusResp struct {
	Status string `json:"status"`
}
