apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: im
  app.kubernetes.io/component: user
resources:
  - user-api-configmap.yaml
  - user-api-deployment.yaml
  - user-api-service.yaml
  - user-rpc-configmap.yaml
  - user-rpc-deployment.yaml
  - user-rpc-service.yaml
