apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    app: user-api
    app.kubernetes.io/name: user-api
    app.kubernetes.io/component: user
spec:
  selector:
    app: user-api
  type: NodePort
  ports:
  - port: 10100
    targetPort: 10100
    nodePort: 30100
    name: http
