// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: conversation.proto

package conversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureDirectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserA         int64                  `protobuf:"varint,1,opt,name=user_a,json=userA,proto3" json:"user_a,omitempty"`
	UserB         int64                  `protobuf:"varint,2,opt,name=user_b,json=userB,proto3" json:"user_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDirectReq) Reset() {
	*x = EnsureDirectReq{}
	mi := &file_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDirectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDirectReq) ProtoMessage() {}

func (x *EnsureDirectReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDirectReq.ProtoReflect.Descriptor instead.
func (*EnsureDirectReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureDirectReq) GetUserA() int64 {
	if x != nil {
		return x.UserA
	}
	return 0
}

func (x *EnsureDirectReq) GetUserB() int64 {
	if x != nil {
		return x.UserB
	}
	return 0
}

type EnsureDirectResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureDirectResp) Reset() {
	*x = EnsureDirectResp{}
	mi := &file_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureDirectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureDirectResp) ProtoMessage() {}

func (x *EnsureDirectResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureDirectResp.ProtoReflect.Descriptor instead.
func (*EnsureDirectResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureDirectResp) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

type UpdateMetaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        string                 `protobuf:"bytes,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	MsgId         int64                  `protobuf:"varint,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Preview       string                 `protobuf:"bytes,4,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaReq) Reset() {
	*x = UpdateMetaReq{}
	mi := &file_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaReq) ProtoMessage() {}

func (x *UpdateMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaReq.ProtoReflect.Descriptor instead.
func (*UpdateMetaReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetaReq) GetConvId() string {
	if x != nil {
		return x.ConvId
	}
	return ""
}

func (x *UpdateMetaReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *UpdateMetaReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *UpdateMetaReq) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

type UpdateMetaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetaResp) Reset() {
	*x = UpdateMetaResp{}
	mi := &file_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetaResp) ProtoMessage() {}

func (x *UpdateMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetaResp.ProtoReflect.Descriptor instead.
func (*UpdateMetaResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{3}
}

var File_conversation_proto protoreflect.FileDescriptor

const file_conversation_proto_rawDesc = "" +
	"\n" +
	"\x12conversation.proto\x12\fconversation\"?\n" +
	"\x0fEnsureDirectReq\x12\x15\n" +
	"\x06user_a\x18\x01 \x01(\x03R\x05userA\x12\x15\n" +
	"\x06user_b\x18\x02 \x01(\x03R\x05userB\"+\n" +
	"\x10EnsureDirectResp\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\"k\n" +
	"\rUpdateMetaReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\tR\x06convId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\x03R\x05msgId\x12\x18\n" +
	"\apreview\x18\x04 \x01(\tR\apreview\"\x10\n" +
	"\x0eUpdateMetaResp2\xa6\x01\n" +
	"\fConversation\x12M\n" +
	"\fEnsureDirect\x12\x1d.conversation.EnsureDirectReq\x1a\x1e.conversation.EnsureDirectResp\x12G\n" +
	"\n" +
	"UpdateMeta\x12\x1b.conversation.UpdateMetaReq\x1a\x1c.conversation.UpdateMetaRespB\x10Z\x0e./conversationb\x06proto3"

var (
	file_conversation_proto_rawDescOnce sync.Once
	file_conversation_proto_rawDescData []byte
)

func file_conversation_proto_rawDescGZIP() []byte {
	file_conversation_proto_rawDescOnce.Do(func() {
		file_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_proto_rawDesc), len(file_conversation_proto_rawDesc)))
	})
	return file_conversation_proto_rawDescData
}

var file_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_conversation_proto_goTypes = []any{
	(*EnsureDirectReq)(nil),  // 0: conversation.EnsureDirectReq
	(*EnsureDirectResp)(nil), // 1: conversation.EnsureDirectResp
	(*UpdateMetaReq)(nil),    // 2: conversation.UpdateMetaReq
	(*UpdateMetaResp)(nil),   // 3: conversation.UpdateMetaResp
}
var file_conversation_proto_depIdxs = []int32{
	0, // 0: conversation.Conversation.EnsureDirect:input_type -> conversation.EnsureDirectReq
	2, // 1: conversation.Conversation.UpdateMeta:input_type -> conversation.UpdateMetaReq
	1, // 2: conversation.Conversation.EnsureDirect:output_type -> conversation.EnsureDirectResp
	3, // 3: conversation.Conversation.UpdateMeta:output_type -> conversation.UpdateMetaResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_conversation_proto_init() }
func file_conversation_proto_init() {
	if File_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_proto_rawDesc), len(file_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_proto_depIdxs,
		MessageInfos:      file_conversation_proto_msgTypes,
	}.Build()
	File_conversation_proto = out.File
	file_conversation_proto_goTypes = nil
	file_conversation_proto_depIdxs = nil
}
