apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: im
  app.kubernetes.io/component: gateway
resources:
  - gateway-api-configmap.yaml
  - gateway-api-deployment.yaml
  - gateway-api-service.yaml
