apiVersion: v1
kind: Service
metadata:
  name: push-api
  labels:
    app: push-api
    app.kubernetes.io/name: push-api
    app.kubernetes.io/component: push
spec:
  selector:
    app: push-api
  type: NodePort
  ports:
  - port: 10700
    targetPort: 10700
    nodePort: 30700
    name: http
