apiVersion: v1
kind: Service
metadata:
  name: push-rpc
  labels:
    app: push-rpc
    app.kubernetes.io/name: push-rpc
    app.kubernetes.io/component: push
spec:
  selector:
    app: push-rpc
  ports:
  - port: 20700
    targetPort: 20700
    name: http
