apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/part-of: im
  app.kubernetes.io/component: message
resources:
  - message-api-configmap.yaml
  - message-api-deployment.yaml
  - message-api-service.yaml
  - message-rpc-configmap.yaml
  - message-rpc-deployment.yaml
  - message-rpc-service.yaml
