apiVersion: v1
kind: ConfigMap
metadata:
  name: message-rpc-config
  labels:
    app.kubernetes.io/name: message-rpc
    app.kubernetes.io/part-of: im
    app.kubernetes.io/component: message
data:
  message-rpc.yaml: |
    Name: message.rpc
    ListenOn: 0.0.0.0:20500
    Postgres:
      DSN: postgres://im:im@host.docker.internal:5432/im?sslmode=disable
    Log:
      ServiceName: message-rpc
      Mode: console
      Level: info
      Stat: false
    GroupRpc:
      Endpoints:
        - group-rpc:20300
    RocketMQ:
      NameServer:
        - host.docker.internal:9876
    RedisStore:
      Addr: host.docker.internal:6379
