apiVersion: v1
kind: Service
metadata:
  name: message-api
  labels:
    app: message-api
    app.kubernetes.io/name: message-api
    app.kubernetes.io/component: message
spec:
  selector:
    app: message-api
  type: NodePort
  ports:
  - port: 10500
    targetPort: 10500
    nodePort: 30500
    name: http
