// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"im/apps/group/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/groups",
				Handler: createGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups/:id",
				Handler: getGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/groups/:id/members",
				Handler: addMembersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/groups/:id/members",
				Handler: listMembersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
