// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ListMessagesReq struct {
	Id        string `path:"id"`
	BeforeSeq int64  `form:"before_seq,optional"`
	Limit     int    `form:"limit,optional"`
}

type ListMessagesResp struct {
	Messages []Message `json:"messages"`
}

type Message struct {
	Id       int64  `json:"id"`
	ConvId   string `json:"conv_id"`
	SenderId int64  `json:"sender_id"`
	Seq      int64  `json:"seq"`
	MsgType  string `json:"msg_type"`
	Content  string `json:"content"`
}
