// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: conversation.proto

package server

import (
	"context"

	"im/apps/conversation/rpc/conversation"
	"im/apps/conversation/rpc/internal/logic"
	"im/apps/conversation/rpc/internal/svc"
)

type ConversationServer struct {
	svcCtx *svc.ServiceContext
	conversation.UnimplementedConversationServer
}

func NewConversationServer(svcCtx *svc.ServiceContext) *ConversationServer {
	return &ConversationServer{
		svcCtx: svcCtx,
	}
}

func (s *ConversationServer) EnsureDirect(ctx context.Context, in *conversation.EnsureDirectReq) (*conversation.EnsureDirectResp, error) {
	l := logic.NewEnsureDirectLogic(ctx, s.svcCtx)
	return l.EnsureDirect(in)
}

func (s *ConversationServer) UpdateMeta(ctx context.Context, in *conversation.UpdateMetaReq) (*conversation.UpdateMetaResp, error) {
	l := logic.NewUpdateMetaLogic(ctx, s.svcCtx)
	return l.UpdateMeta(in)
}
