// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: conversation.proto

package conversation_client

import (
	"context"

	"im/apps/conversation/rpc/conversation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EnsureDirectReq  = conversation.EnsureDirectReq
	EnsureDirectResp = conversation.EnsureDirectResp
	UpdateMetaReq    = conversation.UpdateMetaReq
	UpdateMetaResp   = conversation.UpdateMetaResp

	Conversation interface {
		EnsureDirect(ctx context.Context, in *EnsureDirectReq, opts ...grpc.CallOption) (*EnsureDirectResp, error)
		UpdateMeta(ctx context.Context, in *UpdateMetaReq, opts ...grpc.CallOption) (*UpdateMetaResp, error)
	}

	defaultConversation struct {
		cli zrpc.Client
	}
)

func NewConversation(cli zrpc.Client) Conversation {
	return &defaultConversation{
		cli: cli,
	}
}

func (m *defaultConversation) EnsureDirect(ctx context.Context, in *EnsureDirectReq, opts ...grpc.CallOption) (*EnsureDirectResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.EnsureDirect(ctx, in, opts...)
}

func (m *defaultConversation) UpdateMeta(ctx context.Context, in *UpdateMetaReq, opts ...grpc.CallOption) (*UpdateMetaResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.UpdateMeta(ctx, in, opts...)
}
