// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notification.proto

package notification_client

import (
	"context"

	"im/apps/notification/rpc/notification"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendSystemReq  = notification.SendSystemReq
	SendSystemResp = notification.SendSystemResp

	Notification interface {
		SendSystem(ctx context.Context, in *SendSystemReq, opts ...grpc.CallOption) (*SendSystemResp, error)
	}

	defaultNotification struct {
		cli zrpc.Client
	}
)

func NewNotification(cli zrpc.Client) Notification {
	return &defaultNotification{
		cli: cli,
	}
}

func (m *defaultNotification) SendSystem(ctx context.Context, in *SendSystemReq, opts ...grpc.CallOption) (*SendSystemResp, error) {
	client := notification.NewNotificationClient(m.cli.Conn())
	return client.SendSystem(ctx, in, opts...)
}
