Name: message.rpc
ListenOn: 0.0.0.0:20500
MySQL:
  DSN: im:im@tcp(mysql:3306)/im?parseTime=true&charset=utf8mb4&loc=Local
Log:
  ServiceName: message-rpc
  Mode: console
  Level: info
  Stat: false
GroupRpc:
  Endpoints:
    - group-rpc:20300
RocketMQ:
  NameServer:
    - host.docker.internal:9876
RedisStore:
  Addr: host.docker.internal:6379
