Name: notification.rpc
ListenOn: 0.0.0.0:20600
MySQL:
  DSN: im:im@tcp(mysql:3306)/im?parseTime=true&charset=utf8mb4&loc=Local
Log:
  ServiceName: notification-rpc
  Mode: console
  Level: info
  Stat: false
RocketMQ:
  NameServer:
    - host.docker.internal:9876
