// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package friend_client

import (
	"context"

	"im/apps/friend/rpc/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptFriendReq  = friend.AcceptFriendReq
	AcceptFriendResp = friend.AcceptFriendResp
	AreFriendsReq    = friend.AreFriendsReq
	AreFriendsResp   = friend.AreFriendsResp

	Friend interface {
		AreFriends(ctx context.Context, in *AreFriendsReq, opts ...grpc.CallOption) (*AreFriendsResp, error)
		AcceptFriend(ctx context.Context, in *AcceptFriendReq, opts ...grpc.CallOption) (*AcceptFriendResp, error)
	}

	defaultFriend struct {
		cli zrpc.Client
	}
)

func NewFriend(cli zrpc.Client) Friend {
	return &defaultFriend{
		cli: cli,
	}
}

func (m *defaultFriend) AreFriends(ctx context.Context, in *AreFriendsReq, opts ...grpc.CallOption) (*AreFriendsResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.AreFriends(ctx, in, opts...)
}

func (m *defaultFriend) AcceptFriend(ctx context.Context, in *AcceptFriendReq, opts ...grpc.CallOption) (*AcceptFriendResp, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.AcceptFriend(ctx, in, opts...)
}
