Name: transfer
HealthPort: 10800
MySQL:
  DSN: im:im@tcp(mysql:3306)/im?parseTime=true&charset=utf8mb4&loc=Local
Redis:
  Addr: host.docker.internal:6379
RocketMQ:
  NameServer:
    - host.docker.internal:9876
Transfer:
  InboxMergeMs: 100
  OfflineMergeSec: 10
  MemberBatch: 500
