// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: push.proto

package push_client

import (
	"context"

	"im/apps/push/rpc/push"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GroupSubscribeReq  = push.GroupSubscribeReq
	GroupSubscribeResp = push.GroupSubscribeResp
	SetOnlineReq       = push.SetOnlineReq
	SetOnlineResp      = push.SetOnlineResp

	Push interface {
		SetOnline(ctx context.Context, in *SetOnlineReq, opts ...grpc.CallOption) (*SetOnlineResp, error)
		GroupSubscribe(ctx context.Context, in *GroupSubscribeReq, opts ...grpc.CallOption) (*GroupSubscribeResp, error)
	}

	defaultPush struct {
		cli zrpc.Client
	}
)

func NewPush(cli zrpc.Client) Push {
	return &defaultPush{
		cli: cli,
	}
}

func (m *defaultPush) SetOnline(ctx context.Context, in *SetOnlineReq, opts ...grpc.CallOption) (*SetOnlineResp, error) {
	client := push.NewPushClient(m.cli.Conn())
	return client.SetOnline(ctx, in, opts...)
}

func (m *defaultPush) GroupSubscribe(ctx context.Context, in *GroupSubscribeReq, opts ...grpc.CallOption) (*GroupSubscribeResp, error) {
	client := push.NewPushClient(m.cli.Conn())
	return client.GroupSubscribe(ctx, in, opts...)
}
