apiVersion: v1
kind: Service
metadata:
  name: notification-rpc
  labels:
    app: notification-rpc
    app.kubernetes.io/name: notification-rpc
    app.kubernetes.io/component: notification
spec:
  selector:
    app: notification-rpc
  ports:
  - port: 20600
    targetPort: 20600
    name: http
