apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-rpc-config
  labels:
    app.kubernetes.io/name: notification-rpc
    app.kubernetes.io/part-of: im
    app.kubernetes.io/component: notification
data:
  notification-rpc.yaml: |
    Name: notification.rpc
    ListenOn: 0.0.0.0:20600
    MySQL:
      DSN: im:im@tcp(localhost:3306)/im?parseTime=true&charset=utf8mb4&loc=Local
    Log:
      ServiceName: notification-rpc
      Mode: console
      Level: info
      Stat: false
    RocketMQ:
      NameServer:
        - host.docker.internal:9876
