apiVersion: v1
kind: Service
metadata:
  name: notification-api
  labels:
    app: notification-api
    app.kubernetes.io/name: notification-api
    app.kubernetes.io/component: notification
spec:
  selector:
    app: notification-api
  type: NodePort
  ports:
  - port: 10600
    targetPort: 10600
    nodePort: 30600
    name: http
