apiVersion: v1
kind: Service
metadata:
  name: transfer
  labels:
    app: transfer
    app.kubernetes.io/name: transfer
    app.kubernetes.io/component: transfer
spec:
  selector:
    app: transfer
  type: NodePort
  ports:
  - port: 10800
    targetPort: 10800
    nodePort: 30800
    name: http
