apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: im-local

resources:
  - namespace.yaml
  - apps/gateway
  - apps/user
  - apps/friend
  - apps/group
  - apps/conversation
  - apps/message
  - apps/notification
  - apps/transfer
