// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"im/apps/user/rpc/internal/logic"
	"im/apps/user/rpc/internal/svc"
	"im/apps/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) ValidateToken(ctx context.Context, in *user.ValidateTokenReq) (*user.ValidateTokenResp, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserReq) (*user.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) BatchGetUsers(ctx context.Context, in *user.BatchGetUsersReq) (*user.BatchGetUsersResp, error) {
	l := logic.NewBatchGetUsersLogic(ctx, s.svcCtx)
	return l.BatchGetUsers(in)
}
